### ISSUE TITLE
so pra zua memo e n ter dado creditos

### ISSUE THREAD

**Issue by yiesko** [HitaloSama/payload-dumper#1]
original ae q eu compilei o core
https://github.com/yukosky/ErfanGSIs/tree/sf-runner/payload
klkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

**Comment by yiesko** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKJ

**Comment by HitaloM** [comment]
@yukosky mama
